list_1 = ["NEOUSDT", "LTCUSDT", "ADAUSDT", "EOSUSDT", "IOTAUSDT", "XLMUSDT", "ONTUSDT", "ICXUSDT", "NULSUSDT"]
list_2 = ["ZILUSDT","ERNUSDT","KLAYUSDT","PHAUSDT","BONDUSDT","MLNUSDT","DEXEUSDT","TWTUSDT","ATAUSDT","GTCUSDT","TORNUSDT"]
list_3 = ["FIROUSDT","LITUSDT","SFPUSDT","DODOUSDT","CAKEUSDT","ACMUSDT","BADGERUSDT","FISUSDT","OMUSDT","PONDUSDT","DEGOUSDT"]
list_4 = ["GRTUSDT","ALPACAUSDT","QUICKUSDT","MBOXUSDT","FORUSDT","REQUSDT","LINAUSDT","PERPUSDT","RAMPUSDT","NUUSDT","XVGUSDT"]
list_5 = ["CTSIUSDT","ORNUSDT","UTKUSDT","XVSUSDT","ORNUSDT","XVSUSDT","UNFIUSDT","ROSEUSDT","AVAUSDT","XEMUSDT","SKLUSDT"]
list_6 = ["SUSDUSDT","ALICEUSDT","LPTUSDT","STRAXUSDT","HBARUSDT","KEEPUSDT","BELUSDT","CKBUSDT","CHRUSDT","BALUSDT" ]
list_7 = ["BCCUSDT","XRPUSDT","TUSDUSDT", "TRXUSDT","ETCUSDT","VENUSDT","VETUSDT","SUPERUSDT","CFXUSDT","EPSUSDT","AUTOUSDT"]
list_8 = ["LINKUSDT","WAVESUSDT","ONGUSDT","HOTUSDT","ZRXUSDT","FETUSDT","BATUSDT","FARMUSDT","RSRUSDT","LUNAUSDT"]
list_9 = ["ALGOUSDT","GTOUSDT","ERDUSDT","DOGEUSDT","DUSKUSDT","ANKRUSDT","WINUSDT","COSUSDT","NPXSUSDT","COCOSUSDT","MTLUSDT"]
list_10 = ["WANUSDT","FUNUSDT","CVCUSDT","CHZUSDT","BANDUSDT","BEAMUSDT","XTZUSDT","RENUSDT","RVNUSDT","HCUSDT"]
list_11 = ["CTXCUSDT","BCHUSDT","TROYUSDT","VITEUSDT","FTTUSDT","OGNUSDT","DREPUSDT","BULLUSDT","BEARUSDT","TCTUSDT"]
list_12 = ["VTHOUSDT","DGBUSDT","SXPUSDT","MKRUSDT","DAIUSDT","DCRUSDT","STORJUSDT","MANAUSDT","AUDUSDT"]
list_13 = ["COTIUSDT","STPTUSDT","WTCUSDT","DATAUSDT","XZCUSDT","SOLUSDT","CTSIUSDT","HIVEUSDT","HARDUSDT","DNTUSDT"]
list_14 = ["WNXMUSDT","TRBUSDT","BZRXUSDT","SUSHIUSDT","KSMUSDT","EGLDUSDT","DIAUSDT","RUNEUSDT","FIOUSDT","UMAUSDT"]
list_15 = ["ALPHAUSDT","AAVEUSDT","NEARUSDT","FILUSDT","INJUSDT","AUDIOUSDT","CTKUSDT","AKROUSDT","AXSUSDT"]
list_16 = ["JUVUSDT","PSGUSDT","1INCHUSDT","REEFUSDT","OGUSDT","ATMUSDT","ASRUSDT","CELOUSDT","RIFUSDT","BTCSTUSDT","TRUUSDT"]
list_17 = ["BARUSDT","FORTHUSDT","BAKEUSDT","BURGERUSDT","SLPUSDT","SHIBUSDT","ICPUSDT","ARUSDT","POLSUSDT","MDXUSDT"]
list_18 = ["SCUSDT","ZENUSDT","SNXUSDT","WINGUSDT","UNIUSDT","NBSUSDT","OXTUSDT","SUNUSDT","AVAXUSDT","HNTUSDT","FLMUSDT"]
list_19 = ["GXSUSDT","ARDRUSDT","LENDUSDT","MDTUSDT","STMXUSDT","KNCUSDT","REPUSDT","LRCUSDT","PNTUSDT","COMPUSDT","BKRWUSDT"]
list_20 = ["TRIBEUSDT","GNOUSDT","STXUSDT","KAVAUSDT","ARPAUSDT","IOTXUSDT","RLCUSDT","MCOUSDT","TVKUSDT","MINAUSDT","RAYUSDT"  ]
list_21 = ["BLZUSDT","IRISUSDT","KMDUSDT","JSTUSDT","SRMUSDT","ANTUSDT","CRVUSDT","SANDUSDT","OCEANUSDT","NMRUSDT","DOTUSDT"]
list_22 = ["BTGUSDT","WRXUSDT","BTSUSDT","LSKUSDT","BNTUSDT","LTOUSDT","EOSBULLUSDT","EOSBEARUSDT","STRATUSDT","AIONUSDT","MBLUSDT"]
list_23 = ["TKOUSDT","PUNDIXUSDT","TLMUSDT","XMRUSDT","ZECUSDT","IOSTUSDT","CELRUSDT","DASHUSDT","NANOUSDT","OMGUSDT","MASKUSDT"]
list_24 = ["THETAUSDT","ENJUSDT","MITHUSDT","MATICUSDT","ATOMUSDT","TFUELUSDT","ONEUSDT","FTMUSDT","TOMOUSDT","PERLUSDT"]
list_25 = ["DENTUSDT","MFTUSDT","KEYUSDT","STORMUSDT","DOCKUSDT","C98USDT","CLVUSDT","QNTUSDT","FLOWUSDT","NKNUSDT"]








